FROM nginx:stable-alpine
RUN apk add --no-cache --virtual .build-deps \
    curl \
    openssl \
    jq \
    && curl -s https://api.wott.io/v0.2/ca-bundle | jq -r .ca_bundle  > /etc/ssl/wott-ca.crt \
    && openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096 \
    && apk del --no-cache .build-deps
