version: '3'

services:
  db:
    image: postgres
  django:
    build:
      context: .
      dockerfile: Dockerfile-appserver
    environment:
      DEBUG: 0
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django
