# Generated by Django 2.2.7 on 2019-11-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtls_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenode',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='remotenode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
